// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package io.adetalhouet.order.system.product;

public interface GetProductByIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.adetalhouet.order.system.product.GetProductByIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
