// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package io.adetalhouet.order.system.product;

public interface ProductsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.adetalhouet.order.system.product.Products)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .io.adetalhouet.order.system.product.Product products = 1;</code>
   */
  java.util.List<io.adetalhouet.order.system.product.Product> 
      getProductsList();
  /**
   * <code>repeated .io.adetalhouet.order.system.product.Product products = 1;</code>
   */
  io.adetalhouet.order.system.product.Product getProducts(int index);
  /**
   * <code>repeated .io.adetalhouet.order.system.product.Product products = 1;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .io.adetalhouet.order.system.product.Product products = 1;</code>
   */
  java.util.List<? extends io.adetalhouet.order.system.product.ProductOrBuilder> 
      getProductsOrBuilderList();
  /**
   * <code>repeated .io.adetalhouet.order.system.product.Product products = 1;</code>
   */
  io.adetalhouet.order.system.product.ProductOrBuilder getProductsOrBuilder(
      int index);
}
