// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package io.adetalhouet.order.system.client.grpc;

public final class ClientOuterClass {
  private ClientOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_adetalhouet_order_system_client_grpc_ClientId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_adetalhouet_order_system_client_grpc_ClientId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_adetalhouet_order_system_client_grpc_Clients_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_adetalhouet_order_system_client_grpc_Clients_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_adetalhouet_order_system_client_grpc_Client_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_adetalhouet_order_system_client_grpc_Client_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014client.proto\022\'io.adetalhouet.order.sys" +
      "tem.client.grpc\032\033google/protobuf/empty.p" +
      "roto\032\037google/protobuf/timestamp.proto\"\026\n" +
      "\010ClientId\022\n\n\002id\030\001 \001(\003\"K\n\007Clients\022@\n\007clie" +
      "nts\030\001 \003(\0132/.io.adetalhouet.order.system." +
      "client.grpc.Client\"x\n\006Client\022\n\n\002id\030\001 \001(\003" +
      "\022\r\n\005email\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\022\017\n\007add" +
      "ress\030\004 \001(\t\0220\n\014date_created\030\005 \001(\0132\032.googl" +
      "e.protobuf.Timestamp2\254\003\n\rClientService\022o" +
      "\n\tAddClient\022/.io.adetalhouet.order.syste" +
      "m.client.grpc.Client\0321.io.adetalhouet.or" +
      "der.system.client.grpc.ClientId\022V\n\nGetCl" +
      "ients\022\026.google.protobuf.Empty\0320.io.adeta" +
      "lhouet.order.system.client.grpc.Clients\022" +
      "s\n\rGetClientById\0221.io.adetalhouet.order." +
      "system.client.grpc.ClientId\032/.io.adetalh" +
      "ouet.order.system.client.grpc.Client\022]\n\020" +
      "DeleteClientById\0221.io.adetalhouet.order." +
      "system.client.grpc.ClientId\032\026.google.pro" +
      "tobuf.EmptyB+\n\'io.adetalhouet.order.syst" +
      "em.client.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_io_adetalhouet_order_system_client_grpc_ClientId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_adetalhouet_order_system_client_grpc_ClientId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_adetalhouet_order_system_client_grpc_ClientId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_io_adetalhouet_order_system_client_grpc_Clients_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_adetalhouet_order_system_client_grpc_Clients_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_adetalhouet_order_system_client_grpc_Clients_descriptor,
        new java.lang.String[] { "Clients", });
    internal_static_io_adetalhouet_order_system_client_grpc_Client_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_io_adetalhouet_order_system_client_grpc_Client_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_adetalhouet_order_system_client_grpc_Client_descriptor,
        new java.lang.String[] { "Id", "Email", "Password", "Address", "DateCreated", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
