// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package io.adetalhouet.order.system.client.grpc;

public interface ClientsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.adetalhouet.order.system.client.grpc.Clients)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .io.adetalhouet.order.system.client.grpc.Client clients = 1;</code>
   */
  java.util.List<io.adetalhouet.order.system.client.grpc.Client> 
      getClientsList();
  /**
   * <code>repeated .io.adetalhouet.order.system.client.grpc.Client clients = 1;</code>
   */
  io.adetalhouet.order.system.client.grpc.Client getClients(int index);
  /**
   * <code>repeated .io.adetalhouet.order.system.client.grpc.Client clients = 1;</code>
   */
  int getClientsCount();
  /**
   * <code>repeated .io.adetalhouet.order.system.client.grpc.Client clients = 1;</code>
   */
  java.util.List<? extends io.adetalhouet.order.system.client.grpc.ClientOrBuilder> 
      getClientsOrBuilderList();
  /**
   * <code>repeated .io.adetalhouet.order.system.client.grpc.Client clients = 1;</code>
   */
  io.adetalhouet.order.system.client.grpc.ClientOrBuilder getClientsOrBuilder(
      int index);
}
