// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package io.adetalhouet.order.system.client.grpc;

public interface GetClientByIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.adetalhouet.order.system.client.grpc.GetClientByIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
