// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package io.adetalhouet.order.system.order;

public interface GetOrdersByClientRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.adetalhouet.order.system.order.GetOrdersByClientRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.adetalhouet.order.system.client.Client client = 1;</code>
   * @return Whether the client field is set.
   */
  boolean hasClient();
  /**
   * <code>.io.adetalhouet.order.system.client.Client client = 1;</code>
   * @return The client.
   */
  io.adetalhouet.order.system.client.Client getClient();
  /**
   * <code>.io.adetalhouet.order.system.client.Client client = 1;</code>
   */
  io.adetalhouet.order.system.client.ClientOrBuilder getClientOrBuilder();
}
