// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package io.adetalhouet.order.system.order;

public interface GetOrdersByClientRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.adetalhouet.order.system.order.GetOrdersByClientRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 client_id = 1;</code>
   * @return The clientId.
   */
  long getClientId();
}
