// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package io.adetalhouet.order.system.order;

public interface OrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.adetalhouet.order.system.order.Order)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>.io.adetalhouet.order.system.order.Order.State state = 2;</code>
   * @return The enum numeric value on the wire for state.
   */
  int getStateValue();
  /**
   * <code>.io.adetalhouet.order.system.order.Order.State state = 2;</code>
   * @return The state.
   */
  io.adetalhouet.order.system.order.Order.State getState();

  /**
   * <code>int64 client_id = 3;</code>
   * @return The clientId.
   */
  long getClientId();

  /**
   * <code>int64 cart_id = 4;</code>
   * @return The cartId.
   */
  long getCartId();

  /**
   * <code>.google.protobuf.Timestamp date_created = 5;</code>
   * @return Whether the dateCreated field is set.
   */
  boolean hasDateCreated();
  /**
   * <code>.google.protobuf.Timestamp date_created = 5;</code>
   * @return The dateCreated.
   */
  com.google.protobuf.Timestamp getDateCreated();
  /**
   * <code>.google.protobuf.Timestamp date_created = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDateCreatedOrBuilder();
}
