// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package io.adetalhouet.order.system.order;

public interface OrdersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.adetalhouet.order.system.order.Orders)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .io.adetalhouet.order.system.order.Order orders = 1;</code>
   */
  java.util.List<io.adetalhouet.order.system.order.Order> 
      getOrdersList();
  /**
   * <code>repeated .io.adetalhouet.order.system.order.Order orders = 1;</code>
   */
  io.adetalhouet.order.system.order.Order getOrders(int index);
  /**
   * <code>repeated .io.adetalhouet.order.system.order.Order orders = 1;</code>
   */
  int getOrdersCount();
  /**
   * <code>repeated .io.adetalhouet.order.system.order.Order orders = 1;</code>
   */
  java.util.List<? extends io.adetalhouet.order.system.order.OrderOrBuilder> 
      getOrdersOrBuilderList();
  /**
   * <code>repeated .io.adetalhouet.order.system.order.Order orders = 1;</code>
   */
  io.adetalhouet.order.system.order.OrderOrBuilder getOrdersOrBuilder(
      int index);
}
