// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: billing.proto

package io.adetalhouet.order.system.billing;

/**
 * Protobuf type {@code io.adetalhouet.order.system.billing.Bill}
 */
public  final class Bill extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.adetalhouet.order.system.billing.Bill)
    BillOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Bill.newBuilder() to construct.
  private Bill(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Bill() {
    productIds_ = emptyLongList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Bill();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Bill(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (dateCreated_ != null) {
              subBuilder = dateCreated_.toBuilder();
            }
            dateCreated_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dateCreated_);
              dateCreated_ = subBuilder.buildPartial();
            }

            break;
          }
          case 24: {

            clientId_ = input.readInt64();
            break;
          }
          case 32: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              productIds_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            productIds_.addLong(input.readInt64());
            break;
          }
          case 34: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              productIds_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              productIds_.addLong(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
          case 45: {

            price_ = input.readFloat();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        productIds_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.adetalhouet.order.system.billing.Billing.internal_static_io_adetalhouet_order_system_billing_Bill_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.adetalhouet.order.system.billing.Billing.internal_static_io_adetalhouet_order_system_billing_Bill_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.adetalhouet.order.system.billing.Bill.class, io.adetalhouet.order.system.billing.Bill.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  public long getId() {
    return id_;
  }

  public static final int DATE_CREATED_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp dateCreated_;
  /**
   * <code>.google.protobuf.Timestamp date_created = 2;</code>
   * @return Whether the dateCreated field is set.
   */
  public boolean hasDateCreated() {
    return dateCreated_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp date_created = 2;</code>
   * @return The dateCreated.
   */
  public com.google.protobuf.Timestamp getDateCreated() {
    return dateCreated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateCreated_;
  }
  /**
   * <code>.google.protobuf.Timestamp date_created = 2;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getDateCreatedOrBuilder() {
    return getDateCreated();
  }

  public static final int CLIENT_ID_FIELD_NUMBER = 3;
  private long clientId_;
  /**
   * <code>int64 client_id = 3;</code>
   * @return The clientId.
   */
  public long getClientId() {
    return clientId_;
  }

  public static final int PRODUCT_IDS_FIELD_NUMBER = 4;
  private com.google.protobuf.Internal.LongList productIds_;
  /**
   * <code>repeated int64 product_ids = 4;</code>
   * @return A list containing the productIds.
   */
  public java.util.List<java.lang.Long>
      getProductIdsList() {
    return productIds_;
  }
  /**
   * <code>repeated int64 product_ids = 4;</code>
   * @return The count of productIds.
   */
  public int getProductIdsCount() {
    return productIds_.size();
  }
  /**
   * <code>repeated int64 product_ids = 4;</code>
   * @param index The index of the element to return.
   * @return The productIds at the given index.
   */
  public long getProductIds(int index) {
    return productIds_.getLong(index);
  }
  private int productIdsMemoizedSerializedSize = -1;

  public static final int PRICE_FIELD_NUMBER = 5;
  private float price_;
  /**
   * <code>float price = 5;</code>
   * @return The price.
   */
  public float getPrice() {
    return price_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (dateCreated_ != null) {
      output.writeMessage(2, getDateCreated());
    }
    if (clientId_ != 0L) {
      output.writeInt64(3, clientId_);
    }
    if (getProductIdsList().size() > 0) {
      output.writeUInt32NoTag(34);
      output.writeUInt32NoTag(productIdsMemoizedSerializedSize);
    }
    for (int i = 0; i < productIds_.size(); i++) {
      output.writeInt64NoTag(productIds_.getLong(i));
    }
    if (price_ != 0F) {
      output.writeFloat(5, price_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (dateCreated_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getDateCreated());
    }
    if (clientId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, clientId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < productIds_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(productIds_.getLong(i));
      }
      size += dataSize;
      if (!getProductIdsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      productIdsMemoizedSerializedSize = dataSize;
    }
    if (price_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(5, price_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.adetalhouet.order.system.billing.Bill)) {
      return super.equals(obj);
    }
    io.adetalhouet.order.system.billing.Bill other = (io.adetalhouet.order.system.billing.Bill) obj;

    if (getId()
        != other.getId()) return false;
    if (hasDateCreated() != other.hasDateCreated()) return false;
    if (hasDateCreated()) {
      if (!getDateCreated()
          .equals(other.getDateCreated())) return false;
    }
    if (getClientId()
        != other.getClientId()) return false;
    if (!getProductIdsList()
        .equals(other.getProductIdsList())) return false;
    if (java.lang.Float.floatToIntBits(getPrice())
        != java.lang.Float.floatToIntBits(
            other.getPrice())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    if (hasDateCreated()) {
      hash = (37 * hash) + DATE_CREATED_FIELD_NUMBER;
      hash = (53 * hash) + getDateCreated().hashCode();
    }
    hash = (37 * hash) + CLIENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getClientId());
    if (getProductIdsCount() > 0) {
      hash = (37 * hash) + PRODUCT_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getProductIdsList().hashCode();
    }
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getPrice());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.adetalhouet.order.system.billing.Bill parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.adetalhouet.order.system.billing.Bill parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.adetalhouet.order.system.billing.Bill parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.adetalhouet.order.system.billing.Bill parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.adetalhouet.order.system.billing.Bill parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.adetalhouet.order.system.billing.Bill parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.adetalhouet.order.system.billing.Bill parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.adetalhouet.order.system.billing.Bill parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.adetalhouet.order.system.billing.Bill parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.adetalhouet.order.system.billing.Bill parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.adetalhouet.order.system.billing.Bill parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.adetalhouet.order.system.billing.Bill parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.adetalhouet.order.system.billing.Bill prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.adetalhouet.order.system.billing.Bill}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.adetalhouet.order.system.billing.Bill)
      io.adetalhouet.order.system.billing.BillOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.adetalhouet.order.system.billing.Billing.internal_static_io_adetalhouet_order_system_billing_Bill_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.adetalhouet.order.system.billing.Billing.internal_static_io_adetalhouet_order_system_billing_Bill_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.adetalhouet.order.system.billing.Bill.class, io.adetalhouet.order.system.billing.Bill.Builder.class);
    }

    // Construct using io.adetalhouet.order.system.billing.Bill.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      if (dateCreatedBuilder_ == null) {
        dateCreated_ = null;
      } else {
        dateCreated_ = null;
        dateCreatedBuilder_ = null;
      }
      clientId_ = 0L;

      productIds_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      price_ = 0F;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.adetalhouet.order.system.billing.Billing.internal_static_io_adetalhouet_order_system_billing_Bill_descriptor;
    }

    @java.lang.Override
    public io.adetalhouet.order.system.billing.Bill getDefaultInstanceForType() {
      return io.adetalhouet.order.system.billing.Bill.getDefaultInstance();
    }

    @java.lang.Override
    public io.adetalhouet.order.system.billing.Bill build() {
      io.adetalhouet.order.system.billing.Bill result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.adetalhouet.order.system.billing.Bill buildPartial() {
      io.adetalhouet.order.system.billing.Bill result = new io.adetalhouet.order.system.billing.Bill(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      if (dateCreatedBuilder_ == null) {
        result.dateCreated_ = dateCreated_;
      } else {
        result.dateCreated_ = dateCreatedBuilder_.build();
      }
      result.clientId_ = clientId_;
      if (((bitField0_ & 0x00000001) != 0)) {
        productIds_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.productIds_ = productIds_;
      result.price_ = price_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.adetalhouet.order.system.billing.Bill) {
        return mergeFrom((io.adetalhouet.order.system.billing.Bill)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.adetalhouet.order.system.billing.Bill other) {
      if (other == io.adetalhouet.order.system.billing.Bill.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.hasDateCreated()) {
        mergeDateCreated(other.getDateCreated());
      }
      if (other.getClientId() != 0L) {
        setClientId(other.getClientId());
      }
      if (!other.productIds_.isEmpty()) {
        if (productIds_.isEmpty()) {
          productIds_ = other.productIds_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureProductIdsIsMutable();
          productIds_.addAll(other.productIds_);
        }
        onChanged();
      }
      if (other.getPrice() != 0F) {
        setPrice(other.getPrice());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.adetalhouet.order.system.billing.Bill parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.adetalhouet.order.system.billing.Bill) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp dateCreated_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dateCreatedBuilder_;
    /**
     * <code>.google.protobuf.Timestamp date_created = 2;</code>
     * @return Whether the dateCreated field is set.
     */
    public boolean hasDateCreated() {
      return dateCreatedBuilder_ != null || dateCreated_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp date_created = 2;</code>
     * @return The dateCreated.
     */
    public com.google.protobuf.Timestamp getDateCreated() {
      if (dateCreatedBuilder_ == null) {
        return dateCreated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateCreated_;
      } else {
        return dateCreatedBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp date_created = 2;</code>
     */
    public Builder setDateCreated(com.google.protobuf.Timestamp value) {
      if (dateCreatedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dateCreated_ = value;
        onChanged();
      } else {
        dateCreatedBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp date_created = 2;</code>
     */
    public Builder setDateCreated(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (dateCreatedBuilder_ == null) {
        dateCreated_ = builderForValue.build();
        onChanged();
      } else {
        dateCreatedBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp date_created = 2;</code>
     */
    public Builder mergeDateCreated(com.google.protobuf.Timestamp value) {
      if (dateCreatedBuilder_ == null) {
        if (dateCreated_ != null) {
          dateCreated_ =
            com.google.protobuf.Timestamp.newBuilder(dateCreated_).mergeFrom(value).buildPartial();
        } else {
          dateCreated_ = value;
        }
        onChanged();
      } else {
        dateCreatedBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp date_created = 2;</code>
     */
    public Builder clearDateCreated() {
      if (dateCreatedBuilder_ == null) {
        dateCreated_ = null;
        onChanged();
      } else {
        dateCreated_ = null;
        dateCreatedBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp date_created = 2;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDateCreatedBuilder() {
      
      onChanged();
      return getDateCreatedFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp date_created = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDateCreatedOrBuilder() {
      if (dateCreatedBuilder_ != null) {
        return dateCreatedBuilder_.getMessageOrBuilder();
      } else {
        return dateCreated_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : dateCreated_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp date_created = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDateCreatedFieldBuilder() {
      if (dateCreatedBuilder_ == null) {
        dateCreatedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDateCreated(),
                getParentForChildren(),
                isClean());
        dateCreated_ = null;
      }
      return dateCreatedBuilder_;
    }

    private long clientId_ ;
    /**
     * <code>int64 client_id = 3;</code>
     * @return The clientId.
     */
    public long getClientId() {
      return clientId_;
    }
    /**
     * <code>int64 client_id = 3;</code>
     * @param value The clientId to set.
     * @return This builder for chaining.
     */
    public Builder setClientId(long value) {
      
      clientId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 client_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientId() {
      
      clientId_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList productIds_ = emptyLongList();
    private void ensureProductIdsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        productIds_ = mutableCopy(productIds_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int64 product_ids = 4;</code>
     * @return A list containing the productIds.
     */
    public java.util.List<java.lang.Long>
        getProductIdsList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(productIds_) : productIds_;
    }
    /**
     * <code>repeated int64 product_ids = 4;</code>
     * @return The count of productIds.
     */
    public int getProductIdsCount() {
      return productIds_.size();
    }
    /**
     * <code>repeated int64 product_ids = 4;</code>
     * @param index The index of the element to return.
     * @return The productIds at the given index.
     */
    public long getProductIds(int index) {
      return productIds_.getLong(index);
    }
    /**
     * <code>repeated int64 product_ids = 4;</code>
     * @param index The index to set the value at.
     * @param value The productIds to set.
     * @return This builder for chaining.
     */
    public Builder setProductIds(
        int index, long value) {
      ensureProductIdsIsMutable();
      productIds_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 product_ids = 4;</code>
     * @param value The productIds to add.
     * @return This builder for chaining.
     */
    public Builder addProductIds(long value) {
      ensureProductIdsIsMutable();
      productIds_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 product_ids = 4;</code>
     * @param values The productIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllProductIds(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureProductIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, productIds_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 product_ids = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductIds() {
      productIds_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private float price_ ;
    /**
     * <code>float price = 5;</code>
     * @return The price.
     */
    public float getPrice() {
      return price_;
    }
    /**
     * <code>float price = 5;</code>
     * @param value The price to set.
     * @return This builder for chaining.
     */
    public Builder setPrice(float value) {
      
      price_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float price = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrice() {
      
      price_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.adetalhouet.order.system.billing.Bill)
  }

  // @@protoc_insertion_point(class_scope:io.adetalhouet.order.system.billing.Bill)
  private static final io.adetalhouet.order.system.billing.Bill DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.adetalhouet.order.system.billing.Bill();
  }

  public static io.adetalhouet.order.system.billing.Bill getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Bill>
      PARSER = new com.google.protobuf.AbstractParser<Bill>() {
    @java.lang.Override
    public Bill parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Bill(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Bill> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Bill> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.adetalhouet.order.system.billing.Bill getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

