// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: billing.proto

package io.adetalhouet.order.system.billing;

public final class Billing {
  private Billing() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_adetalhouet_order_system_billing_GetBillByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_adetalhouet_order_system_billing_GetBillByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_adetalhouet_order_system_billing_GetBillByClientRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_adetalhouet_order_system_billing_GetBillByClientRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_adetalhouet_order_system_billing_Bills_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_adetalhouet_order_system_billing_Bills_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_adetalhouet_order_system_billing_Bill_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_adetalhouet_order_system_billing_Bill_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rbilling.proto\022#io.adetalhouet.order.sy" +
      "stem.billing\032\037google/protobuf/timestamp." +
      "proto\032\013utils.proto\032\014client.proto\032\rproduc" +
      "t.proto\" \n\022GetBillByIdRequest\022\n\n\002id\030\001 \001(" +
      "\003\"+\n\026GetBillByClientRequest\022\021\n\tclient_id" +
      "\030\001 \001(\003\"A\n\005Bills\0228\n\005bills\030\001 \003(\0132).io.adet" +
      "alhouet.order.system.billing.Bill\"\317\001\n\004Bi" +
      "ll\022\n\n\002id\030\001 \001(\003\0220\n\014date_created\030\002 \001(\0132\032.g" +
      "oogle.protobuf.Timestamp\022:\n\006client\030\003 \001(\013" +
      "2*.io.adetalhouet.order.system.client.Cl" +
      "ient\022>\n\010products\030\004 \003(\0132,.io.adetalhouet." +
      "order.system.product.Product\022\r\n\005price\030\005 " +
      "\001(\0022\340\002\n\016BillingService\022_\n\007AddBill\022).io.a" +
      "detalhouet.order.system.billing.Bill\032).i" +
      "o.adetalhouet.order.system.utils.Status\022" +
      "q\n\013GetBillById\0227.io.adetalhouet.order.sy" +
      "stem.billing.GetBillByIdRequest\032).io.ade" +
      "talhouet.order.system.billing.Bill\022z\n\017Ge" +
      "tBillByClient\022;.io.adetalhouet.order.sys" +
      "tem.billing.GetBillByClientRequest\032*.io." +
      "adetalhouet.order.system.billing.BillsB\'" +
      "\n#io.adetalhouet.order.system.billingP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          io.adetalhouet.order.system.utils.Utils.getDescriptor(),
          io.adetalhouet.order.system.client.ClientOuterClass.getDescriptor(),
          io.adetalhouet.order.system.product.ProductOuterClass.getDescriptor(),
        });
    internal_static_io_adetalhouet_order_system_billing_GetBillByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_adetalhouet_order_system_billing_GetBillByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_adetalhouet_order_system_billing_GetBillByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_io_adetalhouet_order_system_billing_GetBillByClientRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_adetalhouet_order_system_billing_GetBillByClientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_adetalhouet_order_system_billing_GetBillByClientRequest_descriptor,
        new java.lang.String[] { "ClientId", });
    internal_static_io_adetalhouet_order_system_billing_Bills_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_io_adetalhouet_order_system_billing_Bills_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_adetalhouet_order_system_billing_Bills_descriptor,
        new java.lang.String[] { "Bills", });
    internal_static_io_adetalhouet_order_system_billing_Bill_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_io_adetalhouet_order_system_billing_Bill_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_adetalhouet_order_system_billing_Bill_descriptor,
        new java.lang.String[] { "Id", "DateCreated", "Client", "Products", "Price", });
    com.google.protobuf.TimestampProto.getDescriptor();
    io.adetalhouet.order.system.utils.Utils.getDescriptor();
    io.adetalhouet.order.system.client.ClientOuterClass.getDescriptor();
    io.adetalhouet.order.system.product.ProductOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
