// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: billing.proto

package io.adetalhouet.order.system.billing;

public interface BillOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.adetalhouet.order.system.billing.Bill)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>.google.protobuf.Timestamp date_created = 2;</code>
   * @return Whether the dateCreated field is set.
   */
  boolean hasDateCreated();
  /**
   * <code>.google.protobuf.Timestamp date_created = 2;</code>
   * @return The dateCreated.
   */
  com.google.protobuf.Timestamp getDateCreated();
  /**
   * <code>.google.protobuf.Timestamp date_created = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDateCreatedOrBuilder();

  /**
   * <code>.io.adetalhouet.order.system.client.Client client = 3;</code>
   * @return Whether the client field is set.
   */
  boolean hasClient();
  /**
   * <code>.io.adetalhouet.order.system.client.Client client = 3;</code>
   * @return The client.
   */
  io.adetalhouet.order.system.client.Client getClient();
  /**
   * <code>.io.adetalhouet.order.system.client.Client client = 3;</code>
   */
  io.adetalhouet.order.system.client.ClientOrBuilder getClientOrBuilder();

  /**
   * <code>repeated .io.adetalhouet.order.system.product.Product products = 4;</code>
   */
  java.util.List<io.adetalhouet.order.system.product.Product> 
      getProductsList();
  /**
   * <code>repeated .io.adetalhouet.order.system.product.Product products = 4;</code>
   */
  io.adetalhouet.order.system.product.Product getProducts(int index);
  /**
   * <code>repeated .io.adetalhouet.order.system.product.Product products = 4;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .io.adetalhouet.order.system.product.Product products = 4;</code>
   */
  java.util.List<? extends io.adetalhouet.order.system.product.ProductOrBuilder> 
      getProductsOrBuilderList();
  /**
   * <code>repeated .io.adetalhouet.order.system.product.Product products = 4;</code>
   */
  io.adetalhouet.order.system.product.ProductOrBuilder getProductsOrBuilder(
      int index);

  /**
   * <code>float price = 5;</code>
   * @return The price.
   */
  float getPrice();
}
