// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: billing.proto

package io.adetalhouet.order.system.billing;

public interface GetBillByClientRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.adetalhouet.order.system.billing.GetBillByClientRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 client_id = 1;</code>
   * @return The clientId.
   */
  long getClientId();
}
