// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package io.adetalhouet.order.system.order.grpc;

public interface OrderIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.adetalhouet.order.system.order.grpc.OrderId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
