// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package io.adetalhouet.order.system.order.grpc;

public interface TrackOrderByIdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.adetalhouet.order.system.order.grpc.TrackOrderByIdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>.io.adetalhouet.order.system.order.grpc.Order order = 3;</code>
   * @return Whether the order field is set.
   */
  boolean hasOrder();
  /**
   * <code>.io.adetalhouet.order.system.order.grpc.Order order = 3;</code>
   * @return The order.
   */
  io.adetalhouet.order.system.order.grpc.Order getOrder();
  /**
   * <code>.io.adetalhouet.order.system.order.grpc.Order order = 3;</code>
   */
  io.adetalhouet.order.system.order.grpc.OrderOrBuilder getOrderOrBuilder();
}
