// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart.proto

package io.adetalhouet.order.system.cart.grpc;

public interface CartIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.adetalhouet.order.system.cart.grpc.CartId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 cart_id = 1;</code>
   * @return The cartId.
   */
  long getCartId();
}
