// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart.proto

package io.adetalhouet.order.system.cart.grpc;

public interface CartItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.adetalhouet.order.system.cart.grpc.CartItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 product_id = 1;</code>
   * @return The productId.
   */
  long getProductId();

  /**
   * <code>int32 quantity = 2;</code>
   * @return The quantity.
   */
  int getQuantity();

  /**
   * <code>double total_price = 3;</code>
   * @return The totalPrice.
   */
  double getTotalPrice();
}
