// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart.proto

package io.adetalhouet.order.system.cart.grpc;

public final class CartOuterClass {
  private CartOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_adetalhouet_order_system_cart_grpc_UpdateCartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_adetalhouet_order_system_cart_grpc_UpdateCartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_adetalhouet_order_system_cart_grpc_CartId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_adetalhouet_order_system_cart_grpc_CartId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_adetalhouet_order_system_cart_grpc_CartItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_adetalhouet_order_system_cart_grpc_CartItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_adetalhouet_order_system_cart_grpc_CartItems_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_adetalhouet_order_system_cart_grpc_CartItems_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_adetalhouet_order_system_cart_grpc_Cart_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_adetalhouet_order_system_cart_grpc_Cart_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ncart.proto\022%io.adetalhouet.order.syste" +
      "m.cart.grpc\032\033google/protobuf/empty.proto" +
      "\032\037google/protobuf/timestamp.proto\"c\n\021Upd" +
      "ateCartRequest\022\017\n\007cart_id\030\001 \001(\003\022=\n\004item\030" +
      "\002 \001(\0132/.io.adetalhouet.order.system.cart" +
      ".grpc.CartItem\"\031\n\006CartId\022\017\n\007cart_id\030\001 \001(" +
      "\003\"E\n\010CartItem\022\022\n\nproduct_id\030\001 \001(\003\022\020\n\010qua" +
      "ntity\030\002 \001(\005\022\023\n\013total_price\030\003 \001(\001\"P\n\tCart" +
      "Items\022C\n\ncart_items\030\001 \003(\0132/.io.adetalhou" +
      "et.order.system.cart.grpc.CartItem\"\237\001\n\004C" +
      "art\022\n\n\002id\030\001 \001(\003\022D\n\ncart_items\030\002 \001(\01320.io" +
      ".adetalhouet.order.system.cart.grpc.Cart" +
      "Items\022\023\n\013total_price\030\003 \001(\001\0220\n\014last_updat" +
      "ed\030\005 \001(\0132\032.google.protobuf.Timestamp2\372\002\n" +
      "\013CartService\022S\n\nCreateCart\022\026.google.prot" +
      "obuf.Empty\032-.io.adetalhouet.order.system" +
      ".cart.grpc.CartId\022]\n\tAddToCart\0228.io.adet" +
      "alhouet.order.system.cart.grpc.UpdateCar" +
      "tRequest\032\026.google.protobuf.Empty\022b\n\016Remo" +
      "teFromCart\0228.io.adetalhouet.order.system" +
      ".cart.grpc.UpdateCartRequest\032\026.google.pr" +
      "otobuf.Empty\022S\n\nDeleteCart\022-.io.adetalho" +
      "uet.order.system.cart.grpc.CartId\032\026.goog" +
      "le.protobuf.EmptyB)\n%io.adetalhouet.orde" +
      "r.system.cart.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_io_adetalhouet_order_system_cart_grpc_UpdateCartRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_adetalhouet_order_system_cart_grpc_UpdateCartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_adetalhouet_order_system_cart_grpc_UpdateCartRequest_descriptor,
        new java.lang.String[] { "CartId", "Item", });
    internal_static_io_adetalhouet_order_system_cart_grpc_CartId_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_adetalhouet_order_system_cart_grpc_CartId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_adetalhouet_order_system_cart_grpc_CartId_descriptor,
        new java.lang.String[] { "CartId", });
    internal_static_io_adetalhouet_order_system_cart_grpc_CartItem_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_io_adetalhouet_order_system_cart_grpc_CartItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_adetalhouet_order_system_cart_grpc_CartItem_descriptor,
        new java.lang.String[] { "ProductId", "Quantity", "TotalPrice", });
    internal_static_io_adetalhouet_order_system_cart_grpc_CartItems_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_io_adetalhouet_order_system_cart_grpc_CartItems_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_adetalhouet_order_system_cart_grpc_CartItems_descriptor,
        new java.lang.String[] { "CartItems", });
    internal_static_io_adetalhouet_order_system_cart_grpc_Cart_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_io_adetalhouet_order_system_cart_grpc_Cart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_adetalhouet_order_system_cart_grpc_Cart_descriptor,
        new java.lang.String[] { "Id", "CartItems", "TotalPrice", "LastUpdated", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
