// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart.proto

package io.adetalhouet.order.system.cart.grpc;

public interface CartOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.adetalhouet.order.system.cart.grpc.Cart)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>.io.adetalhouet.order.system.cart.grpc.CartItems cart_items = 2;</code>
   * @return Whether the cartItems field is set.
   */
  boolean hasCartItems();
  /**
   * <code>.io.adetalhouet.order.system.cart.grpc.CartItems cart_items = 2;</code>
   * @return The cartItems.
   */
  io.adetalhouet.order.system.cart.grpc.CartItems getCartItems();
  /**
   * <code>.io.adetalhouet.order.system.cart.grpc.CartItems cart_items = 2;</code>
   */
  io.adetalhouet.order.system.cart.grpc.CartItemsOrBuilder getCartItemsOrBuilder();

  /**
   * <code>double total_price = 3;</code>
   * @return The totalPrice.
   */
  double getTotalPrice();

  /**
   * <code>.google.protobuf.Timestamp last_updated = 4;</code>
   * @return Whether the lastUpdated field is set.
   */
  boolean hasLastUpdated();
  /**
   * <code>.google.protobuf.Timestamp last_updated = 4;</code>
   * @return The lastUpdated.
   */
  com.google.protobuf.Timestamp getLastUpdated();
  /**
   * <code>.google.protobuf.Timestamp last_updated = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getLastUpdatedOrBuilder();
}
