// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart.proto

package io.adetalhouet.order.system.cart.grpc;

/**
 * Protobuf type {@code io.adetalhouet.order.system.cart.grpc.Cart}
 */
public  final class Cart extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.adetalhouet.order.system.cart.grpc.Cart)
    CartOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Cart.newBuilder() to construct.
  private Cart(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Cart() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Cart();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Cart(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            io.adetalhouet.order.system.cart.grpc.CartItems.Builder subBuilder = null;
            if (cartItems_ != null) {
              subBuilder = cartItems_.toBuilder();
            }
            cartItems_ = input.readMessage(io.adetalhouet.order.system.cart.grpc.CartItems.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(cartItems_);
              cartItems_ = subBuilder.buildPartial();
            }

            break;
          }
          case 25: {

            totalPrice_ = input.readDouble();
            break;
          }
          case 34: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (lastUpdated_ != null) {
              subBuilder = lastUpdated_.toBuilder();
            }
            lastUpdated_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(lastUpdated_);
              lastUpdated_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.adetalhouet.order.system.cart.grpc.CartOuterClass.internal_static_io_adetalhouet_order_system_cart_grpc_Cart_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.adetalhouet.order.system.cart.grpc.CartOuterClass.internal_static_io_adetalhouet_order_system_cart_grpc_Cart_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.adetalhouet.order.system.cart.grpc.Cart.class, io.adetalhouet.order.system.cart.grpc.Cart.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  public long getId() {
    return id_;
  }

  public static final int CART_ITEMS_FIELD_NUMBER = 2;
  private io.adetalhouet.order.system.cart.grpc.CartItems cartItems_;
  /**
   * <code>.io.adetalhouet.order.system.cart.grpc.CartItems cart_items = 2;</code>
   * @return Whether the cartItems field is set.
   */
  public boolean hasCartItems() {
    return cartItems_ != null;
  }
  /**
   * <code>.io.adetalhouet.order.system.cart.grpc.CartItems cart_items = 2;</code>
   * @return The cartItems.
   */
  public io.adetalhouet.order.system.cart.grpc.CartItems getCartItems() {
    return cartItems_ == null ? io.adetalhouet.order.system.cart.grpc.CartItems.getDefaultInstance() : cartItems_;
  }
  /**
   * <code>.io.adetalhouet.order.system.cart.grpc.CartItems cart_items = 2;</code>
   */
  public io.adetalhouet.order.system.cart.grpc.CartItemsOrBuilder getCartItemsOrBuilder() {
    return getCartItems();
  }

  public static final int TOTAL_PRICE_FIELD_NUMBER = 3;
  private double totalPrice_;
  /**
   * <code>double total_price = 3;</code>
   * @return The totalPrice.
   */
  public double getTotalPrice() {
    return totalPrice_;
  }

  public static final int LAST_UPDATED_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp lastUpdated_;
  /**
   * <code>.google.protobuf.Timestamp last_updated = 4;</code>
   * @return Whether the lastUpdated field is set.
   */
  public boolean hasLastUpdated() {
    return lastUpdated_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp last_updated = 4;</code>
   * @return The lastUpdated.
   */
  public com.google.protobuf.Timestamp getLastUpdated() {
    return lastUpdated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdated_;
  }
  /**
   * <code>.google.protobuf.Timestamp last_updated = 4;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getLastUpdatedOrBuilder() {
    return getLastUpdated();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (cartItems_ != null) {
      output.writeMessage(2, getCartItems());
    }
    if (totalPrice_ != 0D) {
      output.writeDouble(3, totalPrice_);
    }
    if (lastUpdated_ != null) {
      output.writeMessage(4, getLastUpdated());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (cartItems_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getCartItems());
    }
    if (totalPrice_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, totalPrice_);
    }
    if (lastUpdated_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getLastUpdated());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.adetalhouet.order.system.cart.grpc.Cart)) {
      return super.equals(obj);
    }
    io.adetalhouet.order.system.cart.grpc.Cart other = (io.adetalhouet.order.system.cart.grpc.Cart) obj;

    if (getId()
        != other.getId()) return false;
    if (hasCartItems() != other.hasCartItems()) return false;
    if (hasCartItems()) {
      if (!getCartItems()
          .equals(other.getCartItems())) return false;
    }
    if (java.lang.Double.doubleToLongBits(getTotalPrice())
        != java.lang.Double.doubleToLongBits(
            other.getTotalPrice())) return false;
    if (hasLastUpdated() != other.hasLastUpdated()) return false;
    if (hasLastUpdated()) {
      if (!getLastUpdated()
          .equals(other.getLastUpdated())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    if (hasCartItems()) {
      hash = (37 * hash) + CART_ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getCartItems().hashCode();
    }
    hash = (37 * hash) + TOTAL_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTotalPrice()));
    if (hasLastUpdated()) {
      hash = (37 * hash) + LAST_UPDATED_FIELD_NUMBER;
      hash = (53 * hash) + getLastUpdated().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.adetalhouet.order.system.cart.grpc.Cart parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.adetalhouet.order.system.cart.grpc.Cart parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.adetalhouet.order.system.cart.grpc.Cart parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.adetalhouet.order.system.cart.grpc.Cart parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.adetalhouet.order.system.cart.grpc.Cart parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.adetalhouet.order.system.cart.grpc.Cart parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.adetalhouet.order.system.cart.grpc.Cart parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.adetalhouet.order.system.cart.grpc.Cart parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.adetalhouet.order.system.cart.grpc.Cart parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.adetalhouet.order.system.cart.grpc.Cart parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.adetalhouet.order.system.cart.grpc.Cart parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.adetalhouet.order.system.cart.grpc.Cart parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.adetalhouet.order.system.cart.grpc.Cart prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.adetalhouet.order.system.cart.grpc.Cart}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.adetalhouet.order.system.cart.grpc.Cart)
      io.adetalhouet.order.system.cart.grpc.CartOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.adetalhouet.order.system.cart.grpc.CartOuterClass.internal_static_io_adetalhouet_order_system_cart_grpc_Cart_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.adetalhouet.order.system.cart.grpc.CartOuterClass.internal_static_io_adetalhouet_order_system_cart_grpc_Cart_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.adetalhouet.order.system.cart.grpc.Cart.class, io.adetalhouet.order.system.cart.grpc.Cart.Builder.class);
    }

    // Construct using io.adetalhouet.order.system.cart.grpc.Cart.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      if (cartItemsBuilder_ == null) {
        cartItems_ = null;
      } else {
        cartItems_ = null;
        cartItemsBuilder_ = null;
      }
      totalPrice_ = 0D;

      if (lastUpdatedBuilder_ == null) {
        lastUpdated_ = null;
      } else {
        lastUpdated_ = null;
        lastUpdatedBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.adetalhouet.order.system.cart.grpc.CartOuterClass.internal_static_io_adetalhouet_order_system_cart_grpc_Cart_descriptor;
    }

    @java.lang.Override
    public io.adetalhouet.order.system.cart.grpc.Cart getDefaultInstanceForType() {
      return io.adetalhouet.order.system.cart.grpc.Cart.getDefaultInstance();
    }

    @java.lang.Override
    public io.adetalhouet.order.system.cart.grpc.Cart build() {
      io.adetalhouet.order.system.cart.grpc.Cart result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.adetalhouet.order.system.cart.grpc.Cart buildPartial() {
      io.adetalhouet.order.system.cart.grpc.Cart result = new io.adetalhouet.order.system.cart.grpc.Cart(this);
      result.id_ = id_;
      if (cartItemsBuilder_ == null) {
        result.cartItems_ = cartItems_;
      } else {
        result.cartItems_ = cartItemsBuilder_.build();
      }
      result.totalPrice_ = totalPrice_;
      if (lastUpdatedBuilder_ == null) {
        result.lastUpdated_ = lastUpdated_;
      } else {
        result.lastUpdated_ = lastUpdatedBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.adetalhouet.order.system.cart.grpc.Cart) {
        return mergeFrom((io.adetalhouet.order.system.cart.grpc.Cart)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.adetalhouet.order.system.cart.grpc.Cart other) {
      if (other == io.adetalhouet.order.system.cart.grpc.Cart.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.hasCartItems()) {
        mergeCartItems(other.getCartItems());
      }
      if (other.getTotalPrice() != 0D) {
        setTotalPrice(other.getTotalPrice());
      }
      if (other.hasLastUpdated()) {
        mergeLastUpdated(other.getLastUpdated());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.adetalhouet.order.system.cart.grpc.Cart parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.adetalhouet.order.system.cart.grpc.Cart) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private io.adetalhouet.order.system.cart.grpc.CartItems cartItems_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.adetalhouet.order.system.cart.grpc.CartItems, io.adetalhouet.order.system.cart.grpc.CartItems.Builder, io.adetalhouet.order.system.cart.grpc.CartItemsOrBuilder> cartItemsBuilder_;
    /**
     * <code>.io.adetalhouet.order.system.cart.grpc.CartItems cart_items = 2;</code>
     * @return Whether the cartItems field is set.
     */
    public boolean hasCartItems() {
      return cartItemsBuilder_ != null || cartItems_ != null;
    }
    /**
     * <code>.io.adetalhouet.order.system.cart.grpc.CartItems cart_items = 2;</code>
     * @return The cartItems.
     */
    public io.adetalhouet.order.system.cart.grpc.CartItems getCartItems() {
      if (cartItemsBuilder_ == null) {
        return cartItems_ == null ? io.adetalhouet.order.system.cart.grpc.CartItems.getDefaultInstance() : cartItems_;
      } else {
        return cartItemsBuilder_.getMessage();
      }
    }
    /**
     * <code>.io.adetalhouet.order.system.cart.grpc.CartItems cart_items = 2;</code>
     */
    public Builder setCartItems(io.adetalhouet.order.system.cart.grpc.CartItems value) {
      if (cartItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        cartItems_ = value;
        onChanged();
      } else {
        cartItemsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.io.adetalhouet.order.system.cart.grpc.CartItems cart_items = 2;</code>
     */
    public Builder setCartItems(
        io.adetalhouet.order.system.cart.grpc.CartItems.Builder builderForValue) {
      if (cartItemsBuilder_ == null) {
        cartItems_ = builderForValue.build();
        onChanged();
      } else {
        cartItemsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.io.adetalhouet.order.system.cart.grpc.CartItems cart_items = 2;</code>
     */
    public Builder mergeCartItems(io.adetalhouet.order.system.cart.grpc.CartItems value) {
      if (cartItemsBuilder_ == null) {
        if (cartItems_ != null) {
          cartItems_ =
            io.adetalhouet.order.system.cart.grpc.CartItems.newBuilder(cartItems_).mergeFrom(value).buildPartial();
        } else {
          cartItems_ = value;
        }
        onChanged();
      } else {
        cartItemsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.io.adetalhouet.order.system.cart.grpc.CartItems cart_items = 2;</code>
     */
    public Builder clearCartItems() {
      if (cartItemsBuilder_ == null) {
        cartItems_ = null;
        onChanged();
      } else {
        cartItems_ = null;
        cartItemsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.io.adetalhouet.order.system.cart.grpc.CartItems cart_items = 2;</code>
     */
    public io.adetalhouet.order.system.cart.grpc.CartItems.Builder getCartItemsBuilder() {
      
      onChanged();
      return getCartItemsFieldBuilder().getBuilder();
    }
    /**
     * <code>.io.adetalhouet.order.system.cart.grpc.CartItems cart_items = 2;</code>
     */
    public io.adetalhouet.order.system.cart.grpc.CartItemsOrBuilder getCartItemsOrBuilder() {
      if (cartItemsBuilder_ != null) {
        return cartItemsBuilder_.getMessageOrBuilder();
      } else {
        return cartItems_ == null ?
            io.adetalhouet.order.system.cart.grpc.CartItems.getDefaultInstance() : cartItems_;
      }
    }
    /**
     * <code>.io.adetalhouet.order.system.cart.grpc.CartItems cart_items = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.adetalhouet.order.system.cart.grpc.CartItems, io.adetalhouet.order.system.cart.grpc.CartItems.Builder, io.adetalhouet.order.system.cart.grpc.CartItemsOrBuilder> 
        getCartItemsFieldBuilder() {
      if (cartItemsBuilder_ == null) {
        cartItemsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.adetalhouet.order.system.cart.grpc.CartItems, io.adetalhouet.order.system.cart.grpc.CartItems.Builder, io.adetalhouet.order.system.cart.grpc.CartItemsOrBuilder>(
                getCartItems(),
                getParentForChildren(),
                isClean());
        cartItems_ = null;
      }
      return cartItemsBuilder_;
    }

    private double totalPrice_ ;
    /**
     * <code>double total_price = 3;</code>
     * @return The totalPrice.
     */
    public double getTotalPrice() {
      return totalPrice_;
    }
    /**
     * <code>double total_price = 3;</code>
     * @param value The totalPrice to set.
     * @return This builder for chaining.
     */
    public Builder setTotalPrice(double value) {
      
      totalPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double total_price = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalPrice() {
      
      totalPrice_ = 0D;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp lastUpdated_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> lastUpdatedBuilder_;
    /**
     * <code>.google.protobuf.Timestamp last_updated = 4;</code>
     * @return Whether the lastUpdated field is set.
     */
    public boolean hasLastUpdated() {
      return lastUpdatedBuilder_ != null || lastUpdated_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 4;</code>
     * @return The lastUpdated.
     */
    public com.google.protobuf.Timestamp getLastUpdated() {
      if (lastUpdatedBuilder_ == null) {
        return lastUpdated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdated_;
      } else {
        return lastUpdatedBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 4;</code>
     */
    public Builder setLastUpdated(com.google.protobuf.Timestamp value) {
      if (lastUpdatedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lastUpdated_ = value;
        onChanged();
      } else {
        lastUpdatedBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 4;</code>
     */
    public Builder setLastUpdated(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (lastUpdatedBuilder_ == null) {
        lastUpdated_ = builderForValue.build();
        onChanged();
      } else {
        lastUpdatedBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 4;</code>
     */
    public Builder mergeLastUpdated(com.google.protobuf.Timestamp value) {
      if (lastUpdatedBuilder_ == null) {
        if (lastUpdated_ != null) {
          lastUpdated_ =
            com.google.protobuf.Timestamp.newBuilder(lastUpdated_).mergeFrom(value).buildPartial();
        } else {
          lastUpdated_ = value;
        }
        onChanged();
      } else {
        lastUpdatedBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 4;</code>
     */
    public Builder clearLastUpdated() {
      if (lastUpdatedBuilder_ == null) {
        lastUpdated_ = null;
        onChanged();
      } else {
        lastUpdated_ = null;
        lastUpdatedBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 4;</code>
     */
    public com.google.protobuf.Timestamp.Builder getLastUpdatedBuilder() {
      
      onChanged();
      return getLastUpdatedFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getLastUpdatedOrBuilder() {
      if (lastUpdatedBuilder_ != null) {
        return lastUpdatedBuilder_.getMessageOrBuilder();
      } else {
        return lastUpdated_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdated_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp last_updated = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getLastUpdatedFieldBuilder() {
      if (lastUpdatedBuilder_ == null) {
        lastUpdatedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getLastUpdated(),
                getParentForChildren(),
                isClean());
        lastUpdated_ = null;
      }
      return lastUpdatedBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.adetalhouet.order.system.cart.grpc.Cart)
  }

  // @@protoc_insertion_point(class_scope:io.adetalhouet.order.system.cart.grpc.Cart)
  private static final io.adetalhouet.order.system.cart.grpc.Cart DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.adetalhouet.order.system.cart.grpc.Cart();
  }

  public static io.adetalhouet.order.system.cart.grpc.Cart getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Cart>
      PARSER = new com.google.protobuf.AbstractParser<Cart>() {
    @java.lang.Override
    public Cart parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Cart(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Cart> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Cart> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.adetalhouet.order.system.cart.grpc.Cart getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

