// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart.proto

package io.adetalhouet.order.system.cart.grpc;

public interface UpdateCartRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.adetalhouet.order.system.cart.grpc.UpdateCartRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 cart_id = 1;</code>
   * @return The cartId.
   */
  long getCartId();

  /**
   * <code>.io.adetalhouet.order.system.cart.grpc.CartItem item = 2;</code>
   * @return Whether the item field is set.
   */
  boolean hasItem();
  /**
   * <code>.io.adetalhouet.order.system.cart.grpc.CartItem item = 2;</code>
   * @return The item.
   */
  io.adetalhouet.order.system.cart.grpc.CartItem getItem();
  /**
   * <code>.io.adetalhouet.order.system.cart.grpc.CartItem item = 2;</code>
   */
  io.adetalhouet.order.system.cart.grpc.CartItemOrBuilder getItemOrBuilder();
}
