// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: utils.proto

package io.adetalhouet.order.system.utils;

public interface StatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.adetalhouet.order.system.utils.Status)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.adetalhouet.order.system.utils.Status.State status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.io.adetalhouet.order.system.utils.Status.State status = 1;</code>
   * @return The status.
   */
  io.adetalhouet.order.system.utils.Status.State getStatus();
}
