// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart.proto

package io.adetalhouet.order.system.cart;

public interface CartItemsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.adetalhouet.order.system.cart.CartItems)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .io.adetalhouet.order.system.cart.CartItem cart_items = 1;</code>
   */
  java.util.List<io.adetalhouet.order.system.cart.CartItem> 
      getCartItemsList();
  /**
   * <code>repeated .io.adetalhouet.order.system.cart.CartItem cart_items = 1;</code>
   */
  io.adetalhouet.order.system.cart.CartItem getCartItems(int index);
  /**
   * <code>repeated .io.adetalhouet.order.system.cart.CartItem cart_items = 1;</code>
   */
  int getCartItemsCount();
  /**
   * <code>repeated .io.adetalhouet.order.system.cart.CartItem cart_items = 1;</code>
   */
  java.util.List<? extends io.adetalhouet.order.system.cart.CartItemOrBuilder> 
      getCartItemsOrBuilderList();
  /**
   * <code>repeated .io.adetalhouet.order.system.cart.CartItem cart_items = 1;</code>
   */
  io.adetalhouet.order.system.cart.CartItemOrBuilder getCartItemsOrBuilder(
      int index);
}
