// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart.proto

package io.adetalhouet.order.system.cart;

public final class CartOuterClass {
  private CartOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_adetalhouet_order_system_cart_UpdateCartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_adetalhouet_order_system_cart_UpdateCartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_adetalhouet_order_system_cart_CartItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_adetalhouet_order_system_cart_CartItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_adetalhouet_order_system_cart_Cart_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_adetalhouet_order_system_cart_Cart_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ncart.proto\022 io.adetalhouet.order.syste" +
      "m.cart\032\033google/protobuf/empty.proto\032\037goo" +
      "gle/protobuf/timestamp.proto\"^\n\021UpdateCa" +
      "rtRequest\022\017\n\007cart_id\030\001 \001(\003\0228\n\004item\030\002 \001(\013" +
      "2*.io.adetalhouet.order.system.cart.Cart" +
      "Item\"E\n\010CartItem\022\022\n\nproduct_id\030\001 \001(\003\022\020\n\010" +
      "quantity\030\002 \001(\005\022\023\n\013total_price\030\003 \001(\002\"b\n\004C" +
      "art\022\n\n\002id\030\001 \001(\003\0229\n\005items\030\002 \003(\0132*.io.adet" +
      "alhouet.order.system.cart.CartItem\022\023\n\013to" +
      "tal_price\030\003 \001(\0012\306\001\n\013CartService\022X\n\tAddTo" +
      "Cart\0223.io.adetalhouet.order.system.cart." +
      "UpdateCartRequest\032\026.google.protobuf.Empt" +
      "y\022]\n\016RemoteFromCart\0223.io.adetalhouet.ord" +
      "er.system.cart.UpdateCartRequest\032\026.googl" +
      "e.protobuf.EmptyB$\n io.adetalhouet.order" +
      ".system.cartP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_io_adetalhouet_order_system_cart_UpdateCartRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_adetalhouet_order_system_cart_UpdateCartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_adetalhouet_order_system_cart_UpdateCartRequest_descriptor,
        new java.lang.String[] { "CartId", "Item", });
    internal_static_io_adetalhouet_order_system_cart_CartItem_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_adetalhouet_order_system_cart_CartItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_adetalhouet_order_system_cart_CartItem_descriptor,
        new java.lang.String[] { "ProductId", "Quantity", "TotalPrice", });
    internal_static_io_adetalhouet_order_system_cart_Cart_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_io_adetalhouet_order_system_cart_Cart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_adetalhouet_order_system_cart_Cart_descriptor,
        new java.lang.String[] { "Id", "Items", "TotalPrice", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
