// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart.proto

package io.adetalhouet.order.system.cart;

public interface CartOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.adetalhouet.order.system.cart.Cart)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>.io.adetalhouet.order.system.cart.CartItems cart_items = 2;</code>
   * @return Whether the cartItems field is set.
   */
  boolean hasCartItems();
  /**
   * <code>.io.adetalhouet.order.system.cart.CartItems cart_items = 2;</code>
   * @return The cartItems.
   */
  io.adetalhouet.order.system.cart.CartItems getCartItems();
  /**
   * <code>.io.adetalhouet.order.system.cart.CartItems cart_items = 2;</code>
   */
  io.adetalhouet.order.system.cart.CartItemsOrBuilder getCartItemsOrBuilder();

  /**
   * <code>double total_price = 3;</code>
   * @return The totalPrice.
   */
  double getTotalPrice();
}
