name: Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1

      - name: Build
        run: gradle build

      - name: Test report
        run: gradle jacocoRootReport

      - name: Upload test report
        run: bash <(curl -s https://codecov.io/bash)